Adds prometheus metrics endpoint
teragrep/k8s_01 pull request #24
Opened 2023-05-22 18:13 UTC by StrongestNumber9

2023-05-23 11:55 UTC, StrongestNumber9 commented
Will include the DropWizard stats on the same PR as further commit as they are linked together

2023-05-23 15:20 UTC, StrongestNumber9 commented
Implemented some of the metrics, and they require plenty of review especially with the errors/reconnects/connections part

2023-06-13 09:31 UTC, kortemik commented on src/main/java/com/teragrep/k8s_01/RelpOutput.java
> +        MetricRegistry metricRegistry = SharedMetricRegistries.getOrCreate("default");
pass rather as an object in constructor than singleton getter

2023-06-13 10:16 UTC, kortemik requested changes

2023-06-13 10:23 UTC, StrongestNumber9 commented
Requested fixes done, self approving for now

2023-06-13 10:23 UTC, merged